term.setCursorPos(1,1)
term.clear()
term.setCursorPos(4,4)
print("")
print("")
print("    ____           _        ___    ____  ")
print("   / ___|   ___   | |__    / _ \\  / ___| ")
print("  | |      / _ \\  | '_ \\  | | | | \\___ \\ ")
print("  | |___  | (_) | | |_) | | |_| |  ___) |")
print("   \\____|  \\___/  |_.__/   \\___/  |____/ ")
print("                                         ")
sleep(1)